let projects = [
   {
    name: "Youtube Summarizer",
    imgsrc: "./images/YTT.png",
    github: "https://github.com/ayushmangarg2003/YT_Video_Summarizer",
    website: "https://ytvideosummarizer.streamlit.app/",
    tags: "Machine Learning",
    month: "February",
    year: "2024",
  },
   {
    name: "Calorie Counter",
    imgsrc: "./images/CalCounter.png",
    github: "https://github.com/ayushmangarg2003/Cal_Counter_GeminiVision",
    website: "https://caloriescounter.streamlit.app/",
    tags: "Machine Learning",
    month: "January",
    year: "2024",
  },
   {
    name: "Blogs App",
    imgsrc: "./images/trueblog.png",
    github: "https://github.com/ayushmangarg2003/Blogs_MERN",
    website: "https://blogs-mern-pi.vercel.app/",
    tags: "MERN",
    month: "December",
    year: "2023",
  },
  {
    name: "DocCARE",
    imgsrc: "./images/doccare.png",
    github: "https://github.com/ayushmangarg2003/BookDoc",
    website: "https://book-doc.vercel.app/",
    tags: "MERN",
    month: "November",
    year: "2023",
  },
  {
    name: "Portfolio",
    imgsrc: "./images/portfolio.png",
    github: "https://github.com/ayushmangarg2003/personal_portfolio",
    website: "https://ayushman.vercel.app/",
    tags: "ReactJS",
    month: "August",
    year: "2023",
  },
  {
    name: "TrueBlog",
    imgsrc: "./images/trueblog.png",
    github: "https://github.com/ayushmangarg2003/Blogs_MySQL",
    website: "https://blogs-my-sql.vercel.app/",
    tags: "MySQL",
    month: "April",
    year: "2023",
  },
  {
    name: "Workout App",
    imgsrc: "./images/Workout.png",
    github: "https://github.com/ayushmangarg2003/Workout_app_MERN",
    website: "https://workout-app-mern.vercel.app/",
    tags: "MERN",
    month: "April",
    year: "2023",
  },
  {
    name: "Food Go",
    imgsrc: "./images/FoodGo.png",
    github: "https://github.com/ayushmangarg2003/food_go_mern_frontend",
    website: "https://food-go-mern-frontend.vercel.app/",
    tags: "MERN",
    month: "Mar",
    year: "2023",
  },
  {
    name: "Code Editor",
    imgsrc: "./images/code-editor.png",
    github: "https://github.com/ayushmangarg2003/Code_Editor",
    website: "https://ayushmangarg2003.github.io/Code_Editor/",
    tags: "Javascript ",
    month: "FEB",
    year: "2023",
  },
  {
    name: "Web Agent",
    imgsrc: "./images/WebAgent.png",
    github: "https://github.com/ayushmangarg2003/web-agent-react-styled-components",
    website: "https://web-agent-react-styled-components.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "Portfolio",
    imgsrc: "./images/ReactPortfolio.png",
    github: "https://github.com/ayushmangarg2003/ayushmangarg",
    website: "https://ayushmangarg.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "Crypto Exchange",
    imgsrc: "./images/CryptoExchangeApp.png",
    github: "https://github.com/ayushmangarg2003/crypto-exchange-react-app",
    website: "https://crypto-exchange-react-app.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "MeTube",
    imgsrc: "./images/MeTube.png",
    github: "https://github.com/ayushmangarg2003/MeTube-React-ChakraUi",
    website: "https://me-tube-react-chakra-ui.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "TechGuy",
    imgsrc: "./images/TechGuy.png",
    github: "https://github.com/ayushmangarg2003/Responsive-React-Homepage",
    website: "https://responsive-react-homepage.vercel.app/",
    tags: "SCSS",
    month: "JAN",
    year: "2023",
  },
  {
    name: "Expense Tracker",
    imgsrc: "./images/ExpenseTracker.png",
    github: "https://github.com/ayushmangarg2003/ExpenseTrackerReact",
    website: "https://expense-tracker-react-eight.vercel.app/",
    tags: "ReactJs",
    month: "DEC",
    year: "2022",
  },
  {
    name: "Hackaton Project",
    imgsrc: "./images/UserInterface.png",
    github: "https://github.com/ayushmangarg2003/UserInterface",
    website: "https://user-interface-beta.vercel.app/",
    tags: "Firebase",
    month: "DEC",
    year: "2022",
  },
  {
    name: "TravelArc",
    imgsrc: "./images/TravelArc.png",
    github: "https://github.com/ayushmangarg2003/TravelArc",
    website: "https://travel-arc.vercel.app/",
    tags: "ReactJs",
    month: "DEC",
    year: "2022",
  },
  {
    name: "Memory Game",
    imgsrc: "./images/MemoryGame.png",
    github: "https://github.com/ayushmangarg2003/MemoryGame",
    website: "https://ayushmangarg2003.github.io/MemoryGame/",
    tags: "Javascript",
    month: "DEC",
    year: "2022",
  },
  {
    name: "TicTacToe",
    imgsrc: "./images/TicTacToe.png",
    github: "https://github.com/ayushmangarg2003/TicTacToe",
    website: "https://ayushmangarg2003.github.io/TicTacToe/",
    tags: "Javascript",
    month: "DEC",
    year: "2022",
  },
  {
    name: "VibeTypeApp",
    imgsrc: "./images/VibeTypeApp.png",
    github: "https://github.com/ayushmangarg2003/VibeTypeApp",
    website: "https://ayushmangarg2003.github.io/VibeTypeApp/",
    tags: "ReactJs",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Weather App",
    imgsrc: "./images/WeatherApp.png",
    github: "https://github.com/ayushmangarg2003/WeatherApp",
    website: "https://ayushmangarg2003.github.io/WeatherApp/",
    tags: "Javascript",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Food Recipe App",
    imgsrc: "./images/FoodRecipe.png",
    github: "https://github.com/ayushmangarg2003/FoodRecipeApp",
    website: "https://ayushmangarg2003.github.io/FoodRecipeApp/",
    tags: "Javascript",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Movie Review App",
    imgsrc: "./images/MovieReview.png",
    github: "https://github.com/ayushmangarg2003/MovieReviewApp",
    website: "https://ayushmangarg2003.github.io/MovieReviewApp/",
    tags: "Javascript",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Name It",
    imgsrc: "./images/NameIt.png",
    github: "https://github.com/ayushmangarg2003/NameIt",
    website: "https://ayushmangarg2003.github.io/NameIt/",
    tags: "React",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Personal Portfolio",
    imgsrc: "./images/PersonalPorfolio.png",
    github: "https://github.com/ayushmangarg2003/PersonalPortfolio",
    website: "https://ayushmangarg2003.github.io/PersonalPortfolio/",
    tags: "CSS",
    month: "OCT",
    year: "2022",
  },
  {
    name: "Binary Brains",
    imgsrc: "./images/BinaryBrains.png",
    github: "https://github.com/ayushmangarg2003/BinaryBrains",
    website: "https://ayushmangarg2003.github.io/BinaryBrains/",
    tags: "CSS",
    month: "OCT",
    year: "2022",
  },
  {
    name: "Karobar Website",
    imgsrc: "./images/Karobar.png",
    github: "https://github.com/ayushmangarg2003/karobarwebsite",
    website: "https://ayushmangarg2003.github.io/karobarwebsite/",
    tags: "CSS",
    month: "OCT",
    year: "2022",
  },
  {
    name: "Pocket Mart",
    imgsrc: "./images/PocketMart.png",
    github: "https://github.com/ayushmangarg2003/PocketMart",
    website: "https://ayushmangarg2003.github.io/PocketMart/",
    tags: "CSS",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Word Counter",
    imgsrc: "./images/WordCounter.png",
    github: "https://github.com/ayushmangarg2003/wordCounter",
    website: "https://ayushmangarg2003.github.io/wordCounter/",
    tags: "Javascript",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Music Player",
    imgsrc: "./images/MusicPlayer.png",
    github: "https://github.com/ayushmangarg2003/MusicPlayer",
    website: "https://ayushmangarg2003.github.io/MusicPlayer/",
    tags: "Javascript",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Books To do",
    imgsrc: "./images/BooksToDo.png",
    github: "https://github.com/ayushmangarg2003/BooksToDo",
    website: "https://ayushmangarg2003.github.io/BooksToDo/",
    tags: "Javascript",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Rapido Clone",
    imgsrc: "./images/RapidoClone.png",
    github: "https://github.com/ayushmangarg2003/RapidoClone",
    website: "https://ayushmangarg2003.github.io/RapidoClone/",
    tags: "CSS",
    month: "SEP",
    year: "2022",
  },
  {
    name: "OlaClone",
    imgsrc: "./images/OlaClone.png",
    github: "https://github.com/ayushmangarg2003/OlaClone",
    website: "https://ayushmangarg2003.github.io/OlaClone/",
    tags: "CSS",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Profile Card",
    imgsrc: "./images/ProfileCard.png",
    github: "https://github.com/ayushmangarg2003/profile",
    website: "https://ayushmangarg2003.github.io/profile/",
    tags: "CSS",
    month: "AUG",
    year: "2022",
  },
  {
    name: "Digital Clock",
    imgsrc: "./images/DigitalClock.png",
    github: "https://github.com/ayushmangarg2003/DigitalClock",
    website: "https://ayushmangarg2003.github.io/DigitalClock/",
    tags: "Javascript",
    month: "AUG",
    year: "2022",
  },
  {
    name: "TextUtils",
    imgsrc: "./images/TextUtils.png",
    github: "https://github.com/ayushmangarg2003/textutils",
    website: "https://ayushmangarg2003.github.io/textutils/",
    tags: "React",
    month: "AUG",
    year: "2022",
  },
  {
    name: "Microsoft Clone",
    imgsrc: "./images/MicrosoftClone.png",
    github: "https://github.com/ayushmangarg2003/MicrosoftClone",
    website: "https://ayushmangarg2003.github.io/MicrosoftClone/",
    tags: "CSS",
    month: "AUG",
    year: "2022",
  },
  {
    name: "Tesla Clone",
    imgsrc: "./images/TeslaClone.png",
    github: "https://github.com/ayushmangarg2003/TeslaClone",
    website: "https://ayushmangarg2003.github.io/TeslaClone/",
    tags: "CSS",
    month: "JUL",
    year: "2022",
  },
  {
    name: "Portfolio",
    imgsrc: "./images/PortfolioOld.png",
    github: "https://github.com/ayushmangarg2003/portfolio",
    website: "https://ayushmangarg2003.github.io/portfolio/",
    tags: "CSS",
    month: "JUN",
    year: "2022",
  },
  {
    name: "aCodeBootstrap",
    imgsrc: "./images/aCodeBootstrap.png",
    github: "https://github.com/ayushmangarg2003/aCodebootstrap",
    website: "https://ayushmangarg2003.github.io/aCodebootstrap/",
    tags: "Bootstrap",
    month: "MAY",
    year: "2022",
  },
];













const cardContainer = document.getElementById("cards-container");
projects.forEach((Element) => {
  var cardEl = document.createElement("div");
  cardEl.innerHTML = `
        <div class="tags">${Element.tags}</div>
        <img src="${Element.imgsrc}" alt="">
        <h4 class="project-name">${Element.name}</h4>
        <div class="buttons">
            <button class="btn"><a href= "${Element.github}" target= "_blank">Code</a></button>
            <button class="btn"><a href= "${Element.website}" target= "_blank">Live Demo</a></button>
        </div> 
        <div class="date">${Element.month}, ${Element.year}</div>`;
  cardEl.classList.add("card");
  cardContainer.appendChild(cardEl);
});
