let projects = [
    {
    name: "College Mart",
    imgsrc: "./images/collegemart.png",
    github: "https://github.com/ayushmangarg2003/CollegeMart",
    website: "https://college-mart-amber.vercel.app/",
    tags: "Next.Js",
    month: "Aug-Oct",
    year: "2025",
  },
    {
    name: "Swaagfun",
    imgsrc: "./images/swaagfun.png",
    github: "https://github.com/ayushmangarg2003",
    website: "https://swaagfun.vercel.app/",
    tags: "MERN",
    month: "Jun-Jul",
    year: "2024",
  },
    {
    name: "Homestayz",
    imgsrc: "./images/homestayz.webp",
    github: "https://github.com/ayushmangarg2003/homestayz",
    website: "https://homestayz.vercel.app/",
    tags: "MERN",
    month: "March",
    year: "2024",
  },
   {
    name: "JournalHub",
    imgsrc: "./images/journal.webp",
    github: "https://github.com/ayushmangarg2003/Journal",
    website: "https://journalhub.vercel.app/",
    tags: "MERN",
    month: "February",
    year: "2024",
  },
   {
    name: "PDF Chat",
    imgsrc: "./images/pdfchat.webp",
    github: "https://github.com/ayushmangarg2003/pdf_chat",
    website: "https://github.com/ayushmangarg2003/pdf_chat",
    tags: "Machine Learning",
    month: "February",
    year: "2024",
  },
   {
    name: "Youtube Summarizer",
    imgsrc: "./images/YTT.webp",
    github: "https://github.com/ayushmangarg2003/YT_Video_Summarizer",
    website: "https://github.com/ayushmangarg2003/YT_Video_Summarizer",
    tags: "Machine Learning",
    month: "February",
    year: "2024",
  },
   {
    name: "Calorie Counter",
    imgsrc: "./images/CalCounter.webp",
    github: "https://github.com/ayushmangarg2003/CalorieCounter",
    website: "https://github.com/ayushmangarg2003/CalorieCounter",
    tags: "Machine Learning",
    month: "January",
    year: "2024",
  },
  {
    name: "Currency Bot",
    imgsrc: "./images/CurrCon.webp",
    github: "https://github.com/ayushmangarg2003/currency-converter-bot/",
    website: "https://web.telegram.org/k/#@AyushmanCurrencyBot",
    tags: "Dialog Flow",
    month: "January",
    year: "2024",
  },
   {
    name: "True Blogs",
    imgsrc: "./images/MERNBLOG.webp",
    github: "https://github.com/ayushmangarg2003/Blogs_MERN",
    website: "https://blogs-mern-pi.vercel.app/",
    tags: "MERN",
    month: "December",
    year: "2023",
  },
  {
    name: "DocCARE",
    imgsrc: "./images/doccare.webp",
    github: "https://github.com/ayushmangarg2003/BookDoc",
    website: "https://book-doc.vercel.app/",
    tags: "MERN",
    month: "November",
    year: "2023",
  },
  {
    name: "Portfolio",
    imgsrc: "./images/portfolio.webp",
    github: "https://github.com/ayushmangarg2003/personal_portfolio",
    website: "https://ayushman.vercel.app/",
    tags: "ReactJS",
    month: "August",
    year: "2023",
  },
  
  {
    name: "TrueBlogs App",
    imgsrc: "./images/Blogs_Mob.webp",
    github: "https://github.com/ayushmangarg2003/blogs_mobile",
    website: "https://www.linkedin.com/posts/ayushmangarg_reactnative-nodejs-mongodb-activity-7100354878492868609-PP27?utm_source=share&utm_medium=member_desktop",
    tags: "React Native",
    month: "August",
    year: "2023",
  },
  {
    name: "TravelArc App",
    imgsrc: "./images/TA_Mobile.webp",
    github: "https://github.com/ayushmangarg2003/TravelArc-Mobile",
    website: "https://github.com/ayushmangarg2003/TravelArc-Mobile",
    tags: "React Native",
    month: "August",
    year: "2023",
  },
  {
    name: "Currency Converter App",
    imgsrc: "./images/CCReactnative.webp",
    github: "https://github.com/ayushmangarg2003/currency_converter_react_native",
    website: "https://github.com/ayushmangarg2003/currency_converter_react_native",
    tags: "React Native",
    month: "July",
    year: "2023",
  },
  {
    name: "Password Generator App",
    imgsrc: "./images/PassGen.webp",
    github: "https://github.com/ayushmangarg2003/Password-Generator-ReactNative",
    website: "https://github.com/ayushmangarg2003/Password-Generator-ReactNative",
    tags: "React Native",
    month: "June",
    year: "2023",
  },
  {
    name: "TrueBlog SQL",
    imgsrc: "./images/trueblog.webp",
    github: "https://github.com/ayushmangarg2003/Blogs_MySQL",
    website: "https://blogs-my-sql.vercel.app/",
    tags: "MySQL",
    month: "April",
    year: "2023",
  },
  {
    name: "Workouts",
    imgsrc: "./images/Workout.webp",
    github: "https://github.com/ayushmangarg2003/Workout_app_MERN",
    website: "https://workout-app-mern.vercel.app/",
    tags: "MERN",
    month: "April",
    year: "2023",
  },
  {
    name: "Food Go",
    imgsrc: "./images/FoodGo.webp",
    github: "https://github.com/ayushmangarg2003/food_go_mern_frontend",
    website: "https://food-go-mern-frontend.vercel.app/",
    tags: "MERN",
    month: "Mar",
    year: "2023",
  },
  {
    name: "CodeEditor",
    imgsrc: "./images/code-editor.webp",
    github: "https://github.com/ayushmangarg2003/Code_Editor",
    website: "https://ayushmangarg2003.github.io/Code_Editor/",
    tags: "Javascript ",
    month: "FEB",
    year: "2023",
  },
  {
    name: "Web Agents",
    imgsrc: "./images/WebAgent.webp",
    github: "https://github.com/ayushmangarg2003/web-agent-react-styled-components",
    website: "https://web-agent-react-styled-components.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "Portfolio",
    imgsrc: "./images/ReactPortfolio.webp",
    github: "https://github.com/ayushmangarg2003/ayushmangarg",
    website: "https://ayushmangarg.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "Crypto Exchange",
    imgsrc: "./images/CryptoExchangeApp.webp",
    github: "https://github.com/ayushmangarg2003/crypto-exchange-react-app",
    website: "https://crypto-exchange-react-app.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "MeTube",
    imgsrc: "./images/MeTube.webp",
    github: "https://github.com/ayushmangarg2003/MeTube-React-ChakraUi",
    website: "https://me-tube-react-chakra-ui.vercel.app/",
    tags: "ReactJs",
    month: "JAN",
    year: "2023",
  },
  {
    name: "TechGuy",
    imgsrc: "./images/TechGuy.webp",
    github: "https://github.com/ayushmangarg2003/Responsive-React-Homepage",
    website: "https://responsive-react-homepage.vercel.app/",
    tags: "SCSS",
    month: "JAN",
    year: "2023",
  },
  {
    name: "Expense Tracker",
    imgsrc: "./images/ExpenseTracker.webp",
    github: "https://github.com/ayushmangarg2003/ExpenseTrackerReact",
    website: "https://expense-tracker-react-eight.vercel.app/",
    tags: "ReactJs",
    month: "DEC",
    year: "2022",
  },
  {
    name: "DocOnTap",
    imgsrc: "./images/UserInterface.webp",
    github: "https://github.com/ayushmangarg2003/UserInterface",
    website: "https://user-interface-beta.vercel.app/",
    tags: "Firebase",
    month: "DEC",
    year: "2022",
  },
  {
    name: "TravelArc",
    imgsrc: "./images/TravelArc.webp",
    github: "https://github.com/ayushmangarg2003/TravelArc",
    website: "https://travel-arc.vercel.app/",
    tags: "ReactJs",
    month: "DEC",
    year: "2022",
  },
  {
    name: "Memory Game",
    imgsrc: "./images/MemoryGame.webp",
    github: "https://github.com/ayushmangarg2003/MemoryGame",
    website: "https://ayushmangarg2003.github.io/MemoryGame/",
    tags: "Javascript",
    month: "DEC",
    year: "2022",
  },
  {
    name: "TicTacToe",
    imgsrc: "./images/TicTacToe.webp",
    github: "https://github.com/ayushmangarg2003/TicTacToe",
    website: "https://ayushmangarg2003.github.io/TicTacToe/",
    tags: "Javascript",
    month: "DEC",
    year: "2022",
  },
  {
    name: "Vibe Type",
    imgsrc: "./images/VibeTypeApp.webp",
    github: "https://github.com/ayushmangarg2003/VibeTypeApp",
    website: "https://ayushmangarg2003.github.io/VibeTypeApp/",
    tags: "ReactJs",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Weather",
    imgsrc: "./images/WeatherApp.webp",
    github: "https://github.com/ayushmangarg2003/WeatherApp",
    website: "https://ayushmangarg2003.github.io/WeatherApp/",
    tags: "Javascript",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Food Recipe",
    imgsrc: "./images/FoodRecipe.webp",
    github: "https://github.com/ayushmangarg2003/FoodRecipeApp",
    website: "https://ayushmangarg2003.github.io/FoodRecipeApp/",
    tags: "Javascript",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Movie Reviews",
    imgsrc: "./images/MovieReview.webp",
    github: "https://github.com/ayushmangarg2003/MovieReviewApp",
    website: "https://ayushmangarg2003.github.io/MovieReviewApp/",
    tags: "Javascript",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Name It",
    imgsrc: "./images/NameIt.webp",
    github: "https://github.com/ayushmangarg2003/NameIt",
    website: "https://ayushmangarg2003.github.io/NameIt/",
    tags: "React",
    month: "Nov",
    year: "2022",
  },
  {
    name: "Personal Portfolio",
    imgsrc: "./images/PersonalPorfolio.webp",
    github: "https://github.com/ayushmangarg2003/PersonalPortfolio",
    website: "https://ayushmangarg2003.github.io/PersonalPortfolio/",
    tags: "CSS",
    month: "OCT",
    year: "2022",
  },
  {
    name: "Binary Brains",
    imgsrc: "./images/BinaryBrains.webp",
    github: "https://github.com/ayushmangarg2003/BinaryBrains",
    website: "https://ayushmangarg2003.github.io/BinaryBrains/",
    tags: "CSS",
    month: "OCT",
    year: "2022",
  },
  {
    name: "Karobar",
    imgsrc: "./images/Karobar.webp",
    github: "https://github.com/ayushmangarg2003/karobarwebsite",
    website: "https://ayushmangarg2003.github.io/karobarwebsite/",
    tags: "CSS",
    month: "OCT",
    year: "2022",
  },
  {
    name: "Pocket Mart",
    imgsrc: "./images/PocketMart.webp",
    github: "https://github.com/ayushmangarg2003/PocketMart",
    website: "https://ayushmangarg2003.github.io/PocketMart/",
    tags: "CSS",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Word Counter",
    imgsrc: "./images/WordCounter.webp",
    github: "https://github.com/ayushmangarg2003/wordCounter",
    website: "https://ayushmangarg2003.github.io/wordCounter/",
    tags: "Javascript",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Music Player",
    imgsrc: "./images/MusicPlayer.webp",
    github: "https://github.com/ayushmangarg2003/MusicPlayer",
    website: "https://ayushmangarg2003.github.io/MusicPlayer/",
    tags: "Javascript",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Books To do",
    imgsrc: "./images/BooksToDo.webp",
    github: "https://github.com/ayushmangarg2003/BooksToDo",
    website: "https://ayushmangarg2003.github.io/BooksToDo/",
    tags: "Javascript",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Rapido Clone",
    imgsrc: "./images/RapidoClone.webp",
    github: "https://github.com/ayushmangarg2003/RapidoClone",
    website: "https://ayushmangarg2003.github.io/RapidoClone/",
    tags: "CSS",
    month: "SEP",
    year: "2022",
  },
  {
    name: "OlaClone",
    imgsrc: "./images/OlaClone.webp",
    github: "https://github.com/ayushmangarg2003/OlaClone",
    website: "https://ayushmangarg2003.github.io/OlaClone/",
    tags: "CSS",
    month: "SEP",
    year: "2022",
  },
  {
    name: "Profile Card",
    imgsrc: "./images/ProfileCard.webp",
    github: "https://github.com/ayushmangarg2003/profile",
    website: "https://ayushmangarg2003.github.io/profile/",
    tags: "CSS",
    month: "AUG",
    year: "2022",
  },
  {
    name: "Digital Clock",
    imgsrc: "./images/DigitalClock.webp",
    github: "https://github.com/ayushmangarg2003/DigitalClock",
    website: "https://ayushmangarg2003.github.io/DigitalClock/",
    tags: "Javascript",
    month: "AUG",
    year: "2022",
  },
  {
    name: "TextUtils",
    imgsrc: "./images/TextUtils.webp",
    github: "https://github.com/ayushmangarg2003/textutils",
    website: "https://ayushmangarg2003.github.io/textutils/",
    tags: "React",
    month: "AUG",
    year: "2022",
  },
  {
    name: "Microsoft Clone",
    imgsrc: "./images/MicrosoftClone.webp",
    github: "https://github.com/ayushmangarg2003/MicrosoftClone",
    website: "https://ayushmangarg2003.github.io/MicrosoftClone/",
    tags: "CSS",
    month: "AUG",
    year: "2022",
  },
  {
    name: "Tesla Clone",
    imgsrc: "./images/TeslaClone.webp",
    github: "https://github.com/ayushmangarg2003/TeslaClone",
    website: "https://ayushmangarg2003.github.io/TeslaClone/",
    tags: "CSS",
    month: "JUL",
    year: "2022",
  },
  {
    name: "Portfolio",
    imgsrc: "./images/PortfolioOld.webp",
    github: "https://github.com/ayushmangarg2003/portfolio",
    website: "https://ayushmangarg2003.github.io/portfolio/",
    tags: "CSS",
    month: "JUN",
    year: "2022",
  },
  {
    name: "aCodeBootstrap",
    imgsrc: "./images/aCodeBootstrap.webp",
    github: "https://github.com/ayushmangarg2003/aCodebootstrap",
    website: "https://ayushmangarg2003.github.io/aCodebootstrap/",
    tags: "Bootstrap",
    month: "MAY",
    year: "2022",
  },
];


const cardContainer = document.getElementById("cards-container");
projects.forEach((Element) => {
  var cardEl = document.createElement("div");
  cardEl.innerHTML = `
        <div class="tags">${Element.tags}</div>
        <img src="${Element.imgsrc}" alt="">
        <h4 class="project-name">${Element.name}</h4>
        <div class="buttons">
            <button class="btn"><a href= "${Element.github}" target= "_blank">Code</a></button>
            <button class="btn"><a href= "${Element.website}" target= "_blank">Demo</a></button>
        </div> 
        <div class="date">${Element.month}, ${Element.year}</div>`;
  cardEl.classList.add("card");
  cardContainer.appendChild(cardEl);
});
